lab8/urls.py
from django.urls import path

from . import views
from .views import landpage


app_name = 'lab8'
urlpatterns = [
    path('', landpage, name='landpage'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^story_enam/', include('story_enam.urls')),
    re_path(r'^story_empat/', include('story_empat.urls')),
    re_path(r'', include('lab9.urls')),
    re_path(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
]

story_enam/urls.py
from django.urls import path

from . import views
#from .views import profile
from .views import index
from .views import add_status


app_name = 'story_enam'
urlpatterns = [
    path('', index, name='index'),
    #path('profile', profile, name='profile'),
    path('add_status', views.add_status, name = 'add_status'),
    # path('delete_all', views.delete_all, name='delete_all'),
    # path('result_table', views.result_table, name = 'result_table'),
]

story_enam/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
	homepage_input = models.CharField(max_length=300)

story_enam/forms.py
from django import forms

class Message_Form(forms.Form):
	error_messages = {
        'required': 'Please fill this field',
    }
	attrs = {
		'class': 'form-control'
    }

	homepage_input = forms.CharField(max_length=300, widget=forms.TextInput(attrs=attrs), required=True)

story_enam/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Message
from .forms import Message_Form

# Create your views here.
def index(request):
	response['daftar'] = Message_Form
	return render(request, 'homepage.html', response)

#def profile(request):
#	return render(request, 'profile.html', response)

response = {}
def add_status(request):
	response['daftar'] = Message_Form
	form = Message_Form(request.POST)
	html = 'homepage.html'
	if request.method =='POST':
		response['homepage_input'] = request.POST['homepage_input']
		status = Message(homepage_input=response['homepage_input'])
		status.save()
		response['daftarStatus'] = Message.objects.all()
		return render(request, html, response)
	else:
		return render(request, html, response)

# def result_table(request):
# 	response = {'daftarStatus': Message_Form, 'status': Message.objects.all()}
# 	html = 'homepage.html'
# 	return render(request, html, response)

# def delete_all(request):
# 	Message.objects.all().delete()
# 	return HttpResponseRedirect('result_table')

story_enam/templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Welcome!</title>
	<link rel="stylesheet" type="text/css" href="{%static 'css/base.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body>
	<h1 id="home-title" style="text-align: center; font-size: 60px">Hello, apa kabar?</h1>
	<center><form method="POST" action="{%url 'story_enam:add_status'%}">
		{% csrf_token %}
		{{daftar}}
		<button type="submit" class="save btn btn-default" id="submit-button" style="color: magenta">Submit</button>
	</form>
	<table class="table" border="1">
		<thead>
            <br><br>
            <th style="text-align: center;">Status</th>
        </thead>
        <tbody>
            {% for a in daftarStatus%}
            <tr>
                <td> {{a.homepage_input}} </td>
            </tr>
            {% endfor %}
        </tbody>
	</table>
	</center>
</body>
</html>

story_enam/templates/profile.html
<!DOCTYPE html>
<html>
<head>
	<title>My Profile</title>
</head>
<body>
	<h1>Name: Aurellia Dhya Andini</h1>
	<h1>NPM: 1706022022</h1>
	<h1>Date of birth: July 20th 1999</h1>
	<br><br>
</body>
</html>