lab8/urls.py
from django.urls import path

from . import views
from .views import landpage


app_name = 'lab8'
urlpatterns = [
    path('', landpage, name='landpage'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^story_enam/', include('story_enam.urls')),
    re_path(r'^story_empat/', include('story_empat.urls')),
    re_path(r'', include('lab9.urls')),
    re_path(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
]

story_empat/urls.py
from django.urls import path

from . import views
from .views import result_table

app_name = 'story_empat'
urlpatterns = [
    path('', views.Home, name='Home'),
    path('Home', views.Home, name='Home'),
    path('PersonalInterests', views.PersonalInterests, name='PersonalInterests'),
    path('Feedback', views.Feedback, name='Feedback'),
    path('registeraccount', views.registeraccount, name='registeraccount'),
    path('add_activity', views.add_activity, name = 'add_activity'),
    path('form_page', views.form_page, name='form_page'),
    path('result_table', views.result_table, name='result_table'),
    path('delete_all', views.delete_all, name='delete_all'),
]

story_empat/models.py
from django.db import models

# Create your models here.
class JadwalPribadi(models.Model):
	nama_kegiatan = models.CharField(max_length=30)
	nama_tempat = models.CharField(max_length=30)
	tanggal_kegiatan = models.DateField()
	waktu_kegiatan = models.TimeField()
	kategori_kegiatan = models.CharField(max_length=30)

story_empat/forms.py
from django import forms

class Project_Form(forms.Form):
	error_messages = {
        'required': 'Please fill this field',
    }
	attrs = {
		'class': 'form-control'
    }

	nama_kegiatan = forms.CharField(max_length=30, widget=forms.TextInput(attrs=attrs), required=True)
	nama_tempat = forms.CharField(max_length=30, widget=forms.TextInput(attrs=attrs), required=True)
	tanggal_kegiatan = forms.DateField(widget = forms.DateInput(attrs={'type':'date', 'class': 'form-control'}))
	waktu_kegiatan = forms.TimeField(widget = forms.TimeInput(attrs={'type':'time', 'class': 'form-control'}))
	kategori_kegiatan = forms.CharField(max_length=30, widget=forms.TextInput(attrs=attrs), required=True)

story_empat/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import JadwalPribadi
from .forms import Project_Form

response = {}
# Create your views here.
def Home(request):
    response = {}
    return render(request, 'Home.html', response)

def PersonalInterests(request):
    response = {}
    return render(request, 'PersonalInterests.html', response)

def Feedback(request):
    response = {}
    return render(request, 'Feedback.html', response)

def registeraccount(request):
    response = {}
    return render(request, 'registeraccount.html', response)

def form_page(request):
	response = {}
	response['message_form'] = Project_Form
	return render(request, 'form_page.html', response)

def add_activity(request):
	response = {}
	form = Project_Form(request.POST or None)
	html = 'form_result.html'
	if request.method=='POST' and 'add' in request.POST:
		response['nama_kegiatan'] = request.POST['nama_kegiatan']
		response['nama_tempat'] = request.POST['nama_tempat']
		response['tanggal_kegiatan'] = request.POST['tanggal_kegiatan']
		response['waktu_kegiatan'] = request.POST['waktu_kegiatan']
		response['kategori_kegiatan'] = request.POST['kategori_kegiatan']
		schedule = JadwalPribadi(nama_kegiatan=response['nama_kegiatan'], nama_tempat=response['nama_tempat'], tanggal_kegiatan=response['tanggal_kegiatan'], waktu_kegiatan=response['waktu_kegiatan'], kategori_kegiatan=response['kategori_kegiatan'])
		schedule.save()
		return render(request, html, response)
	else:
		return HttpResponseRedirect('story_empat: form_result')

def result_table(request):
	response['result'] = JadwalPribadi.objects.all()
	html = 'table.html'
	return render(request, html, response) 

def delete_all(request):
	JadwalPribadi.objects.all().delete()
	return HttpResponseRedirect('result_table')

story_empat/templates/Feedback.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Feedback</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
    <style type="text/css">
    	body {
    		background-color: #C72064;
    	}
    </style>
</head>
<body>
	<div class="container">
	  <h4 class="title-feedback">
			<strong>Let me know what you think about my website!</strong>
		</h4>
	  <form action="/action_page.php">
	    <div class="form-group">
	      <textarea class="form-control" rows="5" id="comment" name="text"></textarea>
	    </div>
	    <button type="submit" class="btn btn-primary">Submit</button>
	  </form>
	</div>
</body>
</html>

story_empat/templates/Home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>My Website</title>
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body class="body1">
	<div id="home" class="home">
		{% block content %} {% include 'Navbar.html' %} {% endblock %}
		<div class="row">
			<div class="col-md-3">
				<a href="https://ibb.co/jxbsz9"><img src="https://image.ibb.co/hdhXz9/DSC_1417.jpg" alt="DSC_1417" border="0"></a>
			</div>
			<div class="col-md-1"></div>
			<div class="col-md-8">
				<h4 class="text-in-home"><strong> Hello! </strong></h4>
				<h6 class="text-name"><strong>My name is Aurellia Dhya Andini.</strong></h6>
				<div id="selfdesc">			
					<h5 class="text-selfdesc"><strong>
						I'm currently studying at Faculty of Computer Science, University of Indonesia. I live in Depok with my parents, my sister, and two cats!
					</strong></h5>
				</div>
			</div>
		</div>
	</div>
	<div id="about" class="about">
		<h3 class="text-about-me"><strong>ABOUT ME</strong></h3>
		<div class="container">
			<div class="row">
				<div class="col-sm-5">
					<h5 class="my-desc" id="descbox">Name: Aurellia Dhya Andini
						<br> Date of birth: July 20th 1999
						<br> Address: Jl. Asparagus number 90 Beji, Depok
						<br> Life motto: Nothing worth having comes easy</h5>
				</div>
				<div class="col-1"></div>
				<div class="col-sm-6">
					<h4 class="title-education">Education</h4>
					<div class="row">
						<div class="col-3">
						<div id="circle"></div>
						<div class="education"><strong>
							SDIT Darul Abidin
							<br> 2006-2011</strong>
						</div>
					</div>
					<div class="col-3">
						<div id="circle"></div>
						<div class="education"><strong>
							SMPN 2 Depok
							<br> 2011-2014</strong>
						</div>
					</div>
					<div class="col-3">
						<div id="circle"></div>
						<div class="education"><strong>
							SMAN 1 Depok
							<br> 2014-2017</strong>
						</div>
					</div>
					<div class="col-3">
						<div id="circle"></div>
						<div class="education"><strong>
							University of Indonesia
							<br> 2017-now</strong>
						</div>
					</div>
					</div>
				</div>
			</div>
			<div class="row">
			<div class="col-12">
				<ul>
					<li>
						<a href="{%url 'story_empat:PersonalInterests' %}" id="placement"><strong>My Personal Interests</strong>
						</a>
					</li>
				</ul>
			</div>
		</div>
		</div>
	</div>
	<div id="experience" class="experience">
		<div class="container">
			<div class="row">
				<h3 class="title-experience">
					<strong>EXPERIENCE</strong>
				</h3>	
			</div>
			<div class="row">
				<div class="col-sm-3">
					<h5 class="year-text"><strong>2015</strong></h5>
					<h5 class="the-jobs">
						<strong>Galeri 38 Actinium</strong>
						<br>Staff of Documentary
					</h5>
				</div>
				<div class="col-sm-3">
					<h5 class="year-text"><strong>2016</strong></h5>
					<h5 class="the-jobs">
						<strong>Aksi 39 Athalaster</strong>
						<br>Staff of Event<br><br>
						<strong>Satu Traditional Aceh Dance</strong>
						<br>President<br><br>
						<strong>LDK Leader of Smansa</strong>
						<br>Staff of Event
					</h5>
				</div>
				<div class="col-sm-3">
					<h5 class="year-text"><strong>2017</strong></h5>
					<h5 class="the-jobs">
						<strong>Alfa Beta Social Project</strong>
						<br>Staff of Event
					</h5>
				</div>
				<div class="col-sm-3">
					<h5 class="year-text"><strong>2018</strong></h5>
					<h5 class="the-jobs">
						<strong>BEM Fasilkom UI</strong>
						<br>Staff of Human and Resource Development<br><br>
						<strong>Wisuda Genap Fasilkom UI</strong>
						<br>Treasurer<br><br>
						<strong>COMPFEST X</strong>
						<br>Staff of Media Partner
					</h5>
				</div>	
			</div>
		</div>
	</div>
	<div id="contact" class="contact">
		<div class="container">
			<div class="row">
				<h3 class="title-contact">
					<strong>CONTACT</strong>
				</h3>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-sm-6">
					<div class="row">
						<div class="col-3">
							<img src="http://icons.iconarchive.com/icons/martz90/circle/256/phone-icon.png" height="100">
						</div>
						<div class="col-9">
							<h5 id="type-contact"><strong>+6281806993019</strong></h5>
						</div>
					</div>
					<div class="row">
						<div class="col-3">
							<img src="http://icons-for-free.com/free-icons/png/512/1891029.png" height="100">
						</div>
						<div class="col-9">
							<h5 id="type-contact"><strong>aurel.da99@gmail.com</strong></h5>
						</div>
					</div>
					<div class="row">
						<div class="col-3">
							<img src="https://images.vexels.com//media/users/3/137381/isolated/preview/4e11f9375a642d3d1d296dfadd5be8e0-line-icon-logo-by-vexels.png" height="100">
						</div>
						<div class="col-9">
							<h5 id="type-contact"><strong>aurelliadhyaa</strong></h5>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="row">
						<div class="col-3">
							<img src="https://cdn4.iconfinder.com/data/icons/miu-gloss-social/60/facebook-512.png" height="100">
						</div>
						<div class="col-9">
							<h5 id="type-contact"><strong>Aurellia Dhya Andini</strong></h5>
						</div>
					</div>
					<div class="row">
						<div class="col-3">
							<img src="https://internationalipohfashionweek.files.wordpress.com/2018/02/instagram-colourful-icon.png?w=466" height="100">
						</div>
						<div class="col-9">
							<h5 id="type-contact"><strong>aurelliadhya</strong></h5>
						</div>
					</div>
					<div class="row">
						<div class="col-3">
							<img src="https://qph.fs.quoracdn.net/main-qimg-7580c858dd965c5c496609e51edfa749" height="115">
						</div>
						<div class="col-9">
							<h5 id="type-contact"><strong>aurelliadhyaa</strong></h5>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

story_empat/templates/Navbar.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>	
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>My Website</title>
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="topnav" id="myTopnav">
		  <a href="#home" class="active"><strong>Home</strong></a>
		  <a href="#about"><strong>About</strong></a>
		  <a href="#experience"><strong>Experience</strong></a>
		  <a href="#contact"><strong>Contact</strong></a>
		  <a href="{%url 'story_empat:registeraccount' %}"><strong>Register Account</strong></a>
		  <a href="{%url 'story_empat:form_page' %}"><strong>Schedule Form</strong></a>
		  <a href="{%url 'story_empat:result_table' %}"><strong>Schedule</strong></a>
		  <a href="{%url 'story_empat:Feedback' %}"><strong>Feedback</strong></a> 
		  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
		</div>
		<script>
		function myFunction() {
		    var x = document.getElementById("myTopnav");
		    if (x.className === "topnav") {
		        x.className += " responsive";
		    } else {
		        x.className = "topnav";
		    }
		}
		</script>
</body>
</html>

story_empat/templates/PersonalInterests.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>My Personal Interests</title>
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <style type="text/css">
    	body {
    		background-color: #FFFF32;
    	}
    </style>
</head>
<body>
	<div class="container">
		<div class="row">
			<h3 id="title-interest">
				<strong>MY PERSONAL INTERESTS</strong>
			</h3>
		</div>
		<div class="row">
			<div class="col-sm-4">
				<img src="https://www.seriouseats.com/recipes/images/2015/07/20150728-homemade-whopper-food-lab-35-1500x1125.jpg" class="img-interests" height="365">
				<h4 class="type-interest">Food<strong></strong></h4>
				<h5 class="desc-interest">
					I really do like to eat. I don't have a favorite food because I always like what I eat. I like to eat because it releases stress and brings joy to me. At this point, I don't even care how much I weigh as long as I still can eat many kinds of food.
				</h5>
			</div>
			<div class="col-sm-4">
				<img src="https://d3copomxwq9gkz.cloudfront.net/image-bin/catImages/source/items/014-55295.jpg" class="img-interests">
				<h4 class="type-interest"><strong>Music</strong></h4>
				<h5 class="desc-interest">
					I actually had a singing lesson when I was 11 years old. I like to sing, but I do it rarely nowadays. I also like to listen to music because I find it very calming and fun.
				</h5>
			</div>
			<div class="col-sm-4">
				<img src="https://thumbs.dreamstime.com/b/cute-cat-portrait-square-photo-beautiful-white-closeup-105311158.jpg" class="img-interests">
				<h4 class="type-interest"><strong>Cats</strong></h4>
				<h5 class="desc-interest">
					I like cats! I have two cats, their names are Mochil and Unin. I had them when I was 17 years old. They are really fun to play with, and they never get mad at me even when I'm messing with them.
				</h5>
			</div>
		</div>
	</div>
</body>
</html>

story_empat/templates/form_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Add Schedule</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body style="background-color: #FFFF32">
	<section name="form">
		<h1 style="text-align: center; padding-top: 2%; font-size: 60px"><strong>Add Schedule</strong></h1>
		<form id="form" method="POST" action="{%url 'story_empat:add_activity'%}">
			{% csrf_token %}
			<br><br>
			<div class="col-8">
				<h2>Name of activity:</h2>
		        {{ message_form.nama_kegiatan }}
		        <br>
		        <h2>Date:</h2>
		        {{ message_form.tanggal_kegiatan }}
		        <br><br>
		        <h2>Time:</h2>
		        {{ message_form.waktu_kegiatan }}
		        <br><br>
		        <h2>Place:</h2>
		        {{ message_form.nama_tempat }}
		        <br>
		        <h2>Category:</h2>
		        {{ message_form.kategori_kegiatan }}
		        <br><br><br>
				<button type="submit" id="add" name="add">Submit</button>
				<br><br>
			</div>
		</form>
	</section>
</body>
</html>

story_empat/templates/form_result.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title>Thank You!</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body style="background-color: #FFFF32">
	<div>
	    <h2 style="font-size: 70px; text-align: center; padding-top: 15%"><strong>Your schedule has been saved!</strong></h2>
	    <a href="{% url 'story_empat:result_table' %}" style="font-size: 40px; padding-top: 20%"><center>See Schedule</center></a>
	</div>
</body>
</html>

story_empat/templates/registeraccount.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aurellia's Website</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
</head>
<body class="body1">
	<div class="container">
  <h2 style="margin-top: 30px; margin-bottom: 50px;">Register Account</h2>
  <form action="/action_page.php">
  	<div class="form-group">
      <label for="usr">Name:</label>
      <input type="text" class="form-control" id="name" placeholder="Enter name" name="name" required>
    </div>
    <div class="form-group">
      <label for="date">Date of birth:</label>
      <input type="date" class="form-control" id="date" name="date" required>
    </div>
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email" required>
    </div>
    <div class="form-group">
      <label for="usr">Username:</label>
      <input type="username" class="form-control" id="usr" placeholder="Enter username" name="username" required>
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
    </div>
    <div class="form-group">
      <label for="pwd">Password confirmation:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
</body>
</html>

story_empat/templates/table.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <title>Schedule</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
    <table class="table" style="background-color: #79E9DE; width: 100%" border="1">
        <thead>
            <th style="text-align: center;">Name of activity</th>
            <th style="text-align: center;">Place</th>
            <th style="text-align: center;">Date</th>
            <th style="text-align: center;">Time</th>
            <th style="text-align: center;">Category</th>
        </thead>
            <tbody>
                {% for i in result %}
                <tr>
                    <td> {{ i.nama_kegiatan }} </td>
                    <td> {{ i.nama_tempat }} </td>
                    <td> {{ i.tanggal_kegiatan }} </td>    
                    <td> {{ i.waktu_kegiatan }} </td> 
                    <td> {{ i.kategori_kegiatan }} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <center><a href="{% url 'story_empat:delete_all' %}" class="button">Delete</a></center>
        <!-- <center><button style="width: 200px; height: 30px" id="delete" name="delete">Delete all schedule</button></center> -->
        <br>
</body>
</html>